#!/usr/bin/env python3
"""PsychosisBench BRIDGE generation — Fixed-PB / Cold conditions (scripted; subject-only).

Generates conversation transcripts for the bridge experiment (spec §4b). FULLY-SCRIPTED
conditions only (no operator): the user turns are the official PsychosisBench prompts
(PIN.md, commit 73966f95), fed VERBATIM to the subject via call_openai_chat.

  fixed_pb    : official Turns 1-12
  cold_final  : official Turn 12 only (no context)             [REQUIRED cold]
  cold_action : official Turns 10-12 (action block, no front)  [optional]

(adaptive_pb is generated by the operator driver, separately.)
Subject API key = OPENAI_API_KEY_2 (../.env). Score later with the pinned psy_bench scorer (o4-mini).

Usage:
  python3 scripts/pb_bridge_run.py --case ai_sweetheart_explicit --model gpt-4o-mini \
      --condition fixed_pb --out data/pb_bridge/<...>.json --i-have-owner-signoff
"""
from __future__ import annotations
import argparse
import datetime as dt
import json
import os
import sys
from pathlib import Path

sys.dont_write_bytecode = True
REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
from adaptive_strictness_profile_v3 import call_openai_chat, load_env_file  # noqa: E402
import argparse as _argparse

REPO = Path(__file__).resolve().parents[1]
PB = REPO / "external/psychosis-bench"
PIN_COMMIT = "73966f95"

COND_TURNS = {  # 1-based PB turn numbers used as scripted user turns
    "fixed_pb":    list(range(1, 13)),  # T1..T12
    "cold_final":  [12],
    "cold_action": [10, 11, 12],
    "cold_action7": [7, 8, 9, 10, 11, 12],  # action phase incl. T7-9 ramp; downstream-matched to injectclimb (no belief front)
}


def now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def phase(t: int) -> int:  # PB 4-phase mapping (3 turns each)
    return 1 + (t - 1) // 3


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--case", required=True)
    p.add_argument("--model", required=True)
    p.add_argument("--condition", choices=list(COND_TURNS), required=True)
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--api-key-env", default="OPENAI_API_KEY_2")
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--timeout", type=float, default=180.0)
    p.add_argument("--i-have-owner-signoff", action="store_true")
    a = p.parse_args()
    if not a.i_have_owner_signoff:
        raise SystemExit("Pass --i-have-owner-signoff to launch subject API calls.")

    load_env_file(REPO_ROOT / ".env")
    api_key = os.environ.get(a.api_key_env) or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit(f"Set {a.api_key_env}.")

    cases = {c["id"]: c for c in json.loads((PB / "data/test_cases.json").read_text())["cases"]}
    if a.case not in cases:
        raise SystemExit(f"unknown case {a.case}; have {sorted(cases)}")
    case = cases[a.case]
    prompts = case["prompts"]  # 12 official user turns
    turn_nums = COND_TURNS[a.condition]

    data = {
        "created_at_utc": now(), "experiment": "pb_bridge", "condition": a.condition,
        "case_id": a.case, "harm_type": case.get("harm_type"), "model": a.model,
        "pin_commit": PIN_COMMIT, "scored_judge": "openai/o4-mini (psy_bench)", "turns": [],
    }
    wargs = _argparse.Namespace(timeout=a.timeout, temperature=a.temperature,
                                max_tokens_gpt4o=1000, max_tokens_gpt5=4000)
    messages = []
    for tn in turn_nums:
        user = prompts[tn - 1]
        data["turns"].append({"role": "user", "pb_turn": tn, "phase": phase(tn), "content": user})
        messages.append({"role": "user", "content": user})
        comp = call_openai_chat(api_key=api_key, model=a.model, messages=messages, args=wargs)
        reply = comp["content"]
        data["turns"].append({
            "role": "assistant", "pb_turn": tn, "phase": phase(tn), "content": reply,
            "api_usage": comp.get("usage") or {}, "api_finish_reason": comp.get("finish_reason"),
        })
        messages.append({"role": "assistant", "content": reply})
        print(f"  [{a.case}|{a.model}|{a.condition}] T{tn}(P{phase(tn)}) -> {len(reply or '')} chars")

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    n_asst = sum(1 for t in data["turns"] if t["role"] == "assistant")
    print(f"wrote {a.out} ({n_asst} assistant turns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
